package openrouter_test

const testLongToken = `Chapter I
The Extent of the Empire in the Age of the Antonines Introduction.

The extent and military force of the empire in the age of the Antonines. In the second century of the Christian Era, the empire of Rome comprehended the fairest part of the earth and the most civilized portion of mankind. The frontiers of that extensive monarchy were guarded by ancient renown and disciplined valor. The gentle but powerful influence of laws and manners had gradually cemented the union of the provinces. Their peaceful inhabitants enjoyed and abused the advantages of wealth and luxury. The image of a free constitution was preserved with decent reverence: the Roman senate appeared to possess the sovereign authority, and devolved on the emperors all the executive powers of government. During a happy period of more than fourscore years [a.d. 98–180], the public administration was conducted by the virtue and abilities of Nerva, Trajan, Hadrian, and the two Antonines. It is the design of this, and of the two succeeding chapters, to describe the prosperous condition of their empire; and afterwards, from the death of Marcus Antoninus, to deduce the most important circumstances of its decline and fall, a revolution which will ever be remembered, and is still felt by the nations of the earth.

The principal conquests of the Romans were achieved under the republic; and the emperors, for the most part, were satisfied with preserving those dominions which had been acquired by the policy of the senate, the active emulation of the consuls, and the martial enthusiasm of the people. The seven first centuries were filled with a rapid succession of triumphs; but it was reserved for Augustus to relinquish the ambitious design of subduing the whole earth, and to introduce a spirit of moderation into the public councils. Inclined to peace by his temper and situation, it was easy for him to discover that Rome, in her present exalted situation, had much less to hope than to fear from the chance of arms; and that, in the prosecution of remote wars, the undertaking became every day more difficult, the event more doubtful, and the possession more precarious, and less beneficial.

Happily for the repose of mankind, the moderate system recommended by the wisdom of Augustus was adopted by the fears and vices of his immediate successors. Engaged in the pursuit of pleasure, or in the exercise of tyranny, the first Caesars seldom showed themselves to the armies, or to the provinces; nor were they disposed to suffer that those triumphs which their indolence neglected should be usurped by the conduct and valor of their lieutenants. The military fame of a subject was considered as an insolent invasion of the Imperial prerogative; and it became the duty, as well as interest, of every Roman general to guard the frontiers entrusted to his care without aspiring to conquests which might have proved no less fatal to himself than to the vanquished Barbarians.

The only accession which the Roman empire received during the first century of the Christian Era was the province of Britain. In this single instance, the successors of Caesar and Augustus were persuaded to follow the example of the former, rather than the precept of the latter. The proximity of its situation to the coast of Gaul seemed to invite their arms; the pleasing though doubtful intelligence of a pearl fishery attracted their avarice; and as Britain was viewed in the light of a distinct and insulated world, the conquest scarcely formed any exception to the general system of continental measures. After a war of about forty years, undertaken by the most stupid, maintained by the most dissolute, and terminated by the most timid of all the emperors, the far greater part of the island submitted to the Roman yoke. The various tribes of Britain possessed valor without conduct, and the love of freedom without the spirit of union. They took up arms with savage fierceness; they laid them down, or turned them against each other, with wild inconsistency; and while they fought singly, they were successively subdued. Neither the fortitude of Caractacus, nor the despair of Boadicea, nor the fanaticism of the Druids could avert the slavery of their country, or resist the steady progress of the Imperial generals, who maintained the national glory when the throne was disgraced by the weakest, or the most vicious of mankind. Such was the state of the Roman frontiers, and such the maxims of Imperial policy, from the death of Augustus to the accession of Trajan. That virtuous and active prince had received the education of a soldier and possessed the talents of a general. The peaceful system of his predecessors was interrupted by scenes of war and conquest; and the legions, after a long interval, beheld a military emperor at their head. The first exploits of Trajan were against the Dacians, the most warlike of men, who dwelt beyond the Danube and who, during the reign of Domitian, had insulted with impunity the Majesty of Rome. To the strength and fierceness of Barbarians they added a contempt for life, which was derived from a warm persuasion of the immortality and transmigration of the soul. Decebalus, the Dacian king, approved himself a rival not unworthy of Trajan; nor did he despair of his own and the public fortune till, by the confession of his enemies, he had exhausted every resource both of valor and policy. This memorable war, with a very short suspension of hostilities, lasted five years [a.d. 101–106]; and as the emperor could exert, without control, the whole force of the state, it was terminated by an absolute submission of the Barbarians. The new province of Dacia . . . formed a second exception to the precept of Augustus.

Trajan was ambitious of fame; and as long as mankind shall continue to bestow more liberal applause on their destroyers than on their benefactors, the thirst of military glory will ever be the vice of the most exalted characters. The praises of Alexander, transmitted by a succession of poets and historians, had kindled a dangerous emulation in the mind of Trajan. Like him, the Roman emperor undertook an expedition against the nations of the East; but he lamented with a sigh that his advanced age scarcely left him any hopes of equaling the renown of the son of Philip. Yet the success of Trajan, however transient, was rapid and specious. The degenerate Parthians, broken by intestine discord, fled before his arms. He descended the River Tigris in triumph, from the mountains of Armenia to the Persian Gulf. He enjoyed the honor of being the first, as he was the last, of the Roman generals who ever navigated that remote sea. His fleets ravaged the coast of Arabia; and Trajan vainly flattered himself that he was approaching towards the confines of India. Every day the astonished senate received the intelligence of new names and new nations that acknowledged his sway. They were informed that . . . the rich countries of Armenia, Mesopotamia, and Assyria were reduced into the state of provinces. But the death of Trajan soon clouded the splendid prospect; and it was justly to be dreaded that so many distant nations would throw off the unaccustomed yoke when they were no longer restrained by the powerful hand which had imposed it.

It was an ancient tradition that when the Capitol was founded by one of the Roman kings, the god Terminus (who presided over boundaries, and was represented, according to the fashion of that age, by a large stone) alone, among all the inferior deities, refused to yield his place to Jupiter himself. A favorable inference was drawn from his obstinacy, which was interpreted by the augurs as a sure presage that the boundaries of the Roman power would never recede. During many ages, the prediction, as it is usual, contributed to its own accomplishment. But though Terminus had resisted the majesty of Jupiter, he submitted to the authority of the emperor Hadrian. The resignation of all the eastern conquests of Trajan was the first measure of his reign . . . ; and, in compliance with the precept of Augustus, once more established the Euphrates as the frontier of the empire. Censure, which arraigns the public actions and the private motives of princes, has ascribed to envy a conduct which might be attributed to the prudence and moderation of Hadrian. The various character of that emperor, capable, by turns, of the meanest and the most generous sentiments, may afford some color to the suspicion. It was, however, scarcely in his power to place the superiority of his predecessor in a more conspicuous light than by thus confessing himself unequal to the task of defending the conquests of Trajan.

`
